CC-1126: Add C# support to grep challenge.
codecrafters-io/build-your-own-grep pull request #61
Opened 2024-04-09 14:10 UTC by ryan-gang

2024-04-09 15:19 UTC, rohitpaulk commented on compiled_starters/csharp/src/Program.cs
> +// Uncomment this block to pass the first stage
@ryan-gang can we make the uncommented section shorter? This appears in the UI, so ideally it'd be a small diff, like the Python one:  

<img width="829" alt="Screenshot 2024-04-09 at 16 19 02" src="https://github.com/codecrafters-io/build-your-own-grep/assets/3893573/2bb59b8c-39fc-41c2-9b35-3ee44f476f54">

2024-04-09 15:20 UTC, rohitpaulk commented on compiled_starters/csharp/src/Program.cs
> +// static bool MatchPattern(string inputLine, string pattern)
I don't think this formatting is correct - no empty line above a function definition?

2024-04-09 15:21 UTC, rohitpaulk commented on compiled_starters/csharp/src/Program.cs
> +// static bool MatchPattern(string inputLine, string pattern)
Let's find a C# formatter / linter and try to run it on this - we want code to always look well-formatted

2024-04-09 15:21 UTC, rohitpaulk requested changes
Notes added

2024-04-09 17:26 UTC, ryan-gang commented on compiled_starters/csharp/src/Program.cs
> +// Uncomment this block to pass the first stage
Updated formatting, and reduced diff size.

2024-04-10 08:37 UTC, rohitpaulk commented on compiled_starters/csharp/src/Program.cs
> +// if (MatchPattern(inputLine, pattern)) {
@ryan-gang let's make this even smaller - can we do just the last 5 lines? That'd be similar to what we do for Python

2024-04-10 08:46 UTC, rohitpaulk commented on solutions/csharp/01-init/code/src/Program.cs
> +string pattern = args[1];
@ryan-gang can you confirm how we reviewed formatting here? How do we know that this is C# code that will look "well-formatted" to a senior dev?

2024-04-10 09:53 UTC, ryan-gang commented
Reduced the commented section size further.
Formatted code using `dotnet format`, and added white spaces between blocks.

2024-04-10 12:29 UTC, rohitpaulk approved these changes

2024-04-10 18:16 UTC, merged